name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: 'none'
version: 2.0.7+4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.0.4+1
  rxdart: ^0.25.0
  dio: ^4.0.0-beta7 # for local file test
  path_provider: ^2.0.0
  http: ^0.13.0
  provider: ^5.0.0
  file: ^6.1.0
  flutter_audio_recorder: 0.5.5
  flutter_audio_query: ^0.3.5+6 

dependency_overrides:
  file: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ^2.16.4

  # uncomment to use remote repos
  #assets_audio_player: ^2.0.1
  # assets_audio_player_web: 1.3.5+3

  # uncomment to match local repos
  assets_audio_player:
   path: ../
  #assets_audio_player_web:
  #  path: ../assets_audio_player_web

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
  fonts:
    - family:  AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
